Fixed post-install failure on rpm-ostree distros
rpm-ostree based distros like CoreOS and Silverblue fail at post install scripts. This is because systemctl has been wrapped by the following script that ignores everything in %post except except for preset or --root commands as seen here: https://github.com/coreos/rpm-ostree/blob/main/src/libpriv/systemctl-wrapper.sh

We can just call brave-key-updater directly.

Error:

```
$ rpm-ostree install brave-browser
.
.
.
Running post scripts... done
error: Running %post for brave-keyring: bwrap(/bin/sh): Child process killed by signal 1; run `journalctl -t 'rpm-ostree(brave-keyring.post)'` for more information
```

```
$ journalctl -t 'rpm-ostree(brave-keyring.post)'
.
.
.
Feb 08 17:30:12 aqeel rpm-ostree(brave-keyring.post)[8001]: Redirecting to /bin/systemctl start atd.service
Feb 08 17:30:12 aqeel rpm-ostree(brave-keyring.post)[8001]: rpm-ostree-systemctl: Ignored non-preset command: start atd.service
```